### ISSUE TITLE
Should remove ^ from dependencies in package.json

### ISSUE THREAD

**Issue by mchaov** [daritelska-platforma/frontend#215]
While it is not urgent and super important do be done immediately it is better to have the concrete versions in the [package.json](https://github.com/daritelska-platforma/frontend/blob/master/frontend/package.json) rather than latest. Since I don't see the package-lock in the repo, I assume this is just going to lead to broken builds at some point in time. (I you have the yarn.lock so that's less of an issue).

This article could provide additional motivation to do it: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

**Comment by kachar** [comment]
@mchaov Thanks for bringing up this issue. I do confirm that it's mandatory for the stability and security of the project.

We're using `yarn.lock` instead of `package-lock.json` in to handle the versioning.

As of version 7 npm respects `yarn.lock` as first class member and fulfills the dependencies so we're safe on that end.
https://github.blog/2021-02-02-npm-7-is-now-generally-available/#changes-to-the-lockfile
