### ISSUE TITLE
Integrate form library

### ISSUE THREAD

**Issue by kachar** [daritelska-platforma/frontend#8]
# Motivation

## Viable options

- [ ] https://react-hook-form.com/
- [x] https://formik.org/
- [ ] https://github.com/tannerlinsley/react-form
- [ ] https://final-form.org/react

## Validation libraries

- [ ] https://github.com/colinhacks/zod (TS)
- [x] https://github.com/jquense/yup (JS + [@types/yup](https://www.npmjs.com/package/@types/yup))

## Requirements

- Play well with Material UI (https://material-ui.com/components/text-fields/)
- Has support for validation library with generic types
- Hooks and context integration
- Support for data from MobX stores

https://ora.pm/project/277933/task/4495227

**Comment by Nikola-Andreev** [comment]
I would use the [react-hook-form](https://react-hook-form.com/) without additional validation library, because there are built in validation rules supported:
https://react-hook-form.com/get-started#Applyvalidation

I have experience with [formik](https://formik.org/), but they have 500 opened issues on their [git hub](https://github.com/formium/formik) page 😲.
Currently i am using [react-final-form](https://final-form.org/react), but they also have some bugs and the [repo](https://github.com/final-form/final-form) is rarely updated.

**Comment by kachar** [comment]
The first implementation was brought to master using Formik form lib and Yup as validation lib thanks to @uzuntonev  :raised_hands: 

I'll keep this issue open for any further form or validation related discussions.

The next objectives are:

- Use TS types or interfaces for the form values
- Create generic reusable form binding between MUI text fields and Formik fields
  - To be reused in all internal forms with less verbosity
  - Similar to https://github.com/stackworx/formik-material-ui but less overhead
